### ISSUE TITLE
SteamVR: Recorded played time does not reflect accurate information.

### ISSUE THREAD

**Issue by KWS-Compat** [ValveSoftware/VR-Community-Bugs#135]
SteamVR's hours played are not logged and updated accurately. The number of hours are observed to remain unchanged, regardless of how long the user has run SteamVR.

**Repro Steps**:
1. Launch Steam Client.
2. Navigate to Steam Library and select SteamVR under the 'Tools' section. Observed the hours played.
3. Launch SteamVR again and let it run for 1 hour.
4. Quit the app and return to SteamVR summary screen on the Steam Client. Observe that the hours played remain unchanged.

**Expected Result**:
SteamVR's played hours reflect the amount of time the player has had the application active.
**Actual Result**:
SteamVR's played hours remain unchanged regardless of time played.

**Observed Configs**:
The issue is not hardware related.
Observed on CPU: AMD Ryzen 5 1600X, Intel i7-7700K, AMD 7 1700
Observed on GPU: Nvidia GTX 1080, AMD RX 580, Nvidia GTX 1080 Ti

**Builds**:
SteamVR Beta Build: 1.3.14159
Steam Client Build: 1551832902

**Comment by kisak-valve** [comment]
Doesn't this info conflict with #4?

**Comment by KWS-Compat** [comment]
> Doesn't this info conflict with #4?

That's correct, issue #4 is no longer occurring. We are unable to close #4 due to it having been written by another user, and unfortunately due to this issue having been found near the end of our shift we neglected to comment on #4 detailing the change in behaviour. This has been corrected now. Our apologies for any confusion this caused.

**Comment by KWS-Compat** [comment]
The issue is still occurring as of:
SteamVR Beta Build 1.5.4
Steam Client Build:  1556574584

**Comment by KWS-Compat** [comment]
The issue is still occurring as of:
SteamVR Beta Build 1.7.15
Steam Client Build: 1566431379

**Comment by KWS-Compat** [comment]
The issue was observed to no longer occur as of:
SteamVR Beta Build: 1.8.4
Steam Client Beta Build: 1568941497
