### ISSUE TITLE
SteamVR: VR View window is flickering between SteamVR Home and SteamVR Compositor while HMD is idle while in SteamVR Home environment

### ISSUE THREAD

**Issue by KWS-Compat** [ValveSoftware/VR-Community-Bugs#228]
When the "Pause rendering when headset is idle" option is disabled, VR View window flickers between SteamVR Compositor Environment and SteamVR Home. Flickering keeps occurring until the user moves the HMD. There is no image displayed inside the headset during the idle.

**Repro Steps:**
1. Launch SteamVR.
2. Uncheck the "Pause rendering when headset is idle" option in the Developer settings.
3. Turn on Display VR View option under SteamVR Status window settings.
4. Place the HMD on flat stable surface ensuring the HMD does not move.
5. Wait until the VR View starts flickering. Observe that the mirror windows flickers continuously between SteamVR Home and SteamVR Compositor environment.

**Repro Rate:** 5/5

**Expected Result:**
The headset stops rendering and a black screen displayed in VR View window and an image is displayed in the Dock VR View.

**Actual Result:**
VR View window flickers continuously between SteamVR Home and Compositor Environment.

**Note:**
*The issue doesn't occur when a VR title is running. 
*The issue has similar behaviour to the previously closed ticket #79.

**Observed Configurations:**
Observed on CPU: AMD Ryzen TR 2920X
Observed on GPU: GTX 980
Observed on HMD: HTC Vive

**Builds:**
SteamVR Beta Build: 1.8.2
Steam Client Beta Build: Sept 16 2019

**Comment by kisak-valve** [comment]
Hello @KWS-Compat, per "Fix occasional flicker in headset view in Standby when ‘Pause rendering when headset is idle’ is unchecked." in the [SteamVR 1.8.5 beta](https://steamcommunity.com/games/250820/announcements/detail/1590257408678807014) update, please retest this issue.

**Comment by KWS-Compat** [comment]
> Hello @KWS-Compat, per "Fix occasional flicker in headset view in Standby when ‘Pause rendering when headset is idle’ is unchecked." in the [SteamVR 1.8.5 beta](https://steamcommunity.com/games/250820/announcements/detail/1590257408678807014) update, please retest this issue.

Hello @kisak-valve, we retested the issue and we can confirm that it is no longer occurring in the SteamVR Beta 1.8.5 build. Thank you for the update.
