### ISSUE TITLE
SteamVR - Library Update - Oculus Rift: Closing SteamVR causes it to enter a Reboot Loop.

### ISSUE THREAD

**Issue by KWS-Compat** [ValveSoftware/VR-Community-Bugs#233]
After exiting, SteamVR will begin a reboot loop in the Updated Library. SteamVR will repeatedly begin to display as running but fail to fully launch, then switch back to displaying as not running. While it is displayed as running the user will be unable to manually launch SteamVR or perform any other actions such as verifying files or uninstalling the application. However, if the user attempts to perform these actions while SteamVR is displayed as not running they will be carried out as normal.

The length of this behaviour varies, lasting anywhere from less than a minute after exiting to several minutes. Additionally this behaviour can appear to cease for periods of time, with SteamVR displayed normally as not running, only to begin again.

**Repro Steps:**
1. Launch SteamVR.
2. Allow SteamVR to fully load.
3. Exit SteamVR.
4. In the Updated Library, observe the SteamVR application. Observe that it repeatedly launches and exits, but never fully launches.

**Repro Rate:** 5/5

**Expected Result:** Title fully exits upon closing and does not attempt to launch without user input.
**Actual Result:** Title repeatedly launches and exits.

**Observed Configurations:**
Observed on CPU: AMD Ryzen 7 1700
Observed on GPU: AMD RX 480
Observed on HMD: Oculus Rift

**Builds:**
SteamVR Beta Build: 1.8.3
Steam Client Version: 1568741045

**Comment by BPHardware** [comment]
Similar report from a user with a Windows Mixed Reality headset: 

https://help.steampowered.com/en/ticketmaster/ticket/HT-V9KC-NQ69-JJMX

Uninstalling the WMR for SteamVR software caused the issue to stop, and issue resumed after reinstalling the software and restarting the Steam Client. Using SteamVR software is possible, however this behavior is causing other performance issues on his system.

**Comment by BPHardware** [comment]
Two other community reports of similar problems involving WMR and SteamVR continually opening and closing:

https://steamcommunity.com/app/250820/discussions/3/1626286205690317898/
https://steamcommunity.com/groups/SteamClientBeta/discussions/0/1627412171718764182/

**Comment by KWS-Compat** [comment]
Issue has been observed to no longer occur as of SteamVR Version 1.8.14.
