### ISSUE TITLE
SteamVR fail while trying to make screenshot when async mode is disabled.

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/VR-Community-Bugs#236]
SteamVR fail while trying to make screenshot when async mode is disabled(vrmonitor://debugcommands/async_mode_toggle).

![image](https://user-images.githubusercontent.com/12216723/65584727-c388f080-df9a-11e9-8155-af9efb679a3f.png)

Observed Config:
GTX 1080Ti/i7-8700K
Windows 10
Index headset
SteamVR Beta version: 1.8.5
VR apps: Eleven: Table Tennis VR, Contractors (Most likely it will be possible to observe in any VR application)

**Comment by KWS-Compat** [comment]
We can confirm that the issue also occurs on our configurations.

While async reprojection is disabled, SteamVR will crash after the user attempts to take a screenshot using the "Trigger + System " chord. However, the issue does not occur when the user takes a screenshot using the command prompts in the Debug Commands menu including screenshot_all_request and screenshot_request.

**Repro Steps:**
1. Launch SteamVR.
2. On the SteamVR Status drop-down menu, navigate to Developer tab.
3. Select Debug Commands.
4. Select async_mode_toggle command.
5. Launch any VR title or SteamVR Home.
6. Use "Trigger + System" chord to take a screenshot. Observe that SteamVR will crash immediately and return an error message indicating SteamVR has encountered an unexpected problem (-203)

**Repro Rate:** 5/5

**Expected Result:**
While async reprojection is disabled, taking a screenshot using the motion controller will capture a screenshot and SteamVR remains running without issue.

**Actual Result:**
While async reprojection is disabled, taking a screenshot using the motion controller will crash SteamVR immediately and return a (-203) error message indicating SteamVR has failed.

**Notes:**
This issue also occurs on HMD that do not have async reprojection such as the Oculus Rift and Windows MR which will cause SteamVR to crash immediately after taking a screenshot.

**Observed Configurations:**
Observed on CPU: AMD Threadripper 2920X, Intel i7-7700K
Observed on GPU: Nvidia GTX 980, Nvidia RTX 2070
Observed on HMD: HTC Vive, HTC Vive Pro, Oculus Rift, Windows MR

**Builds:**
SteamVR Beta Build 1.8.5

**Comment by KWS-Compat** [comment]
Hello @sergioberg, 

A SteamVR beta update (1.8.6) was pushed yesterday which mentions a fix for this issue. However, we observed that the behavior for this issue has changed. When async reprojection is disabled, pressing the "Trigger + System" chord will not take any screenshot.

Additionally, the screenshot capturing function using the Oculus Rifts and WMR is no longer working.

This change of behavior is reported in a separate ticket #237 .
