### ISSUE TITLE
Unable to start SteamVR beta in Steam beta

### ISSUE THREAD

**Issue by sergioberg** [ValveSoftware/VR-Community-Bugs#239]
![image](https://user-images.githubusercontent.com/12216723/65718278-a77d7000-e0bc-11e9-9198-c56fe8ddc433.png)

SteamVR not starting from new library (Steam beta)
If start it from a folder manually - it starting. But from the library - not possible. It is showing that it is already running. 
But there are no SteamVR processes.
Restarting Steam - does not help.

SteamVR beta 1.8.6
Steam Beta (Steam Client Beta - September 26, 2019)

**Comment by KWS-Compat** [comment]
@sergioberg 

This behaviour sounds like it may be related to Github #233, in particular SteamVR falsely appearing as running and being unable to start. Can you confirm if any of the additional behaviours described are occurring?

Additionally, would you be able to provide your PC specifications and HMD?

**Comment by sergioberg** [comment]
No additional behaviours. Just switching to beta of Steam. After update - SteamVR always "running", like on screenshot. During update headset was connected. Disconnecting power - doesn't solve the issue. This is my second try to switch to beta. First time when New Library was released in beta - there was same issue (that time i was unable also update SteamVR beta) (https://steamcommunity.com/app/250820/discussions/3/2564160288807896131/)

HMD - Valve Index.
Windows 10/i7-8700K/1080Ti/RAM: 32GB

**Comment by sergioberg** [comment]
Seems like i fix this issue by updating Viveport application.

**Comment by sergioberg** [comment]
Again same issue. This (see logs) happens right after Steam start. SteamVR - "running", but there are no SteamVR processes.

vrclient_rundll32.txt

Tue Oct 01 2019 19:04:49.151 - //==============================================================================================
Tue Oct 01 2019 19:04:49.151 - ================================================================================================
Tue Oct 01 2019 19:04:49.151 - ================================================================================================
Tue Oct 01 2019 19:04:49.151 - rundll32.exe 1.8.6 startup with PID=30340, config=D:\games\steam\config, runtime=D:\games\steam\steamapps\common\SteamVR
Tue Oct 01 2019 19:04:49.151 - vrclient type=VRApplication_Utility
Tue Oct 01 2019 19:04:49.154 - Skipping external driver D:\games\steam\steamapps\common\SteamVRKnucklesDriver because it is not a directory
Tue Oct 01 2019 19:04:49.154 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\htc\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.155 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.155 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\null\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.155 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\MixedRealityVRDriver\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.155 - [Settings] Load Default Json Settings from C:\Program Files\DisplayLink XR\displaylink\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.155 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.156 - [Settings] Load Json Settings from D:\games\steam\config\steamvr.vrsettings
Tue Oct 01 2019 19:04:49.156 - Starting vrserver process: D:\games\steam\steamapps\common\SteamVR\bin\win64\vrserver.exe
Tue Oct 01 2019 19:04:49.175 - CSharedResourceNamespaceClient::Init(): failed connect
Tue Oct 01 2019 19:04:49.175 - CSharedResourceNamespaceClient::Init(): waiting for vrserver for namespace initialization, retries=100
Tue Oct 01 2019 19:04:49.286 - Closing pipe SteamVR_Namespace because it was broken from the other end
Tue Oct 01 2019 19:04:49.286 - CSharedResourceNamespaceClient::Init(): received namespace data 24652
Tue Oct 01 2019 19:04:49.401 - Received success response from vrserver connect
Tue Oct 01 2019 19:04:49.402 - Not looking for a good app key because Steam didn't start this app
Tue Oct 01 2019 19:04:49.402 - App key after connect message:system.generated.rundll32.exe
Tue Oct 01 2019 19:04:49.983 - VR_Shutdown called


vrserver.txt

Tue Oct 01 2019 19:04:49.207 - //==============================================================================================
Tue Oct 01 2019 19:04:49.207 - ================================================================================================
Tue Oct 01 2019 19:04:49.207 - ================================================================================================
Tue Oct 01 2019 19:04:49.207 - vrserver.exe 1.8.6 startup with PID=24652, config=D:\games\steam\config, runtime=D:\games\steam\steamapps\common\SteamVR
Tue Oct 01 2019 19:04:49.208 - CSharedResourceNamespaceServer starting up
Tue Oct 01 2019 19:04:49.208 - CSharedResourceNamespaceClient::Init(): failed connect
Tue Oct 01 2019 19:04:49.208 - CSharedResourceNamespaceClient::Init(): waiting for vrserver for namespace initialization, retries=100
Tue Oct 01 2019 19:04:49.286 - CSharedResourceNamespaceServer sent namespace data: 24652
Tue Oct 01 2019 19:04:49.319 - CSharedResourceNamespaceServer sent namespace data: 24652
Tue Oct 01 2019 19:04:49.319 - Closing pipe SteamVR_Namespace because it was broken from the other end
Tue Oct 01 2019 19:04:49.319 - CSharedResourceNamespaceClient::Init(): received namespace data 24652
Tue Oct 01 2019 19:04:49.319 - Self queried namespace: 24652
Tue Oct 01 2019 19:04:49.319 - VR server 1.8.6 (v1569459536) starting up with config=D:\games\steam\config
Tue Oct 01 2019 19:04:49.321 - Skipping external driver D:\games\steam\steamapps\common\SteamVRKnucklesDriver because it is not a directory
Tue Oct 01 2019 19:04:49.322 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\htc\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.322 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.322 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\null\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.322 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\MixedRealityVRDriver\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.322 - [Settings] Load Default Json Settings from C:\Program Files\DisplayLink XR\displaylink\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.323 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.323 - [Settings] Load Json Settings from D:\games\steam\config\steamvr.vrsettings
Tue Oct 01 2019 19:04:49.327 - [Settings] Load Default Json Settings from C:\Program Files\DisplayLink XR\displaylink\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.327 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\MixedRealityVRDriver\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.327 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\htc\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.327 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\lighthouse\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.327 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\drivers\null\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.327 - [Settings] Load Default Json Settings from D:\games\steam\steamapps\common\SteamVR\resources\settings\default.vrsettings
Tue Oct 01 2019 19:04:49.328 - [Settings] Load Json Settings from D:\games\steam\config\steamvr.vrsettings
Tue Oct 01 2019 19:04:49.384 - Adding controller type vive_controller
Tue Oct 01 2019 19:04:49.384 - Adding controller type oculus_touch
Tue Oct 01 2019 19:04:49.385 - Adding controller type knuckles
Tue Oct 01 2019 19:04:49.386 - Add Json firmware manifest from {htc}/firmware/manifest.vrfirmware
Tue Oct 01 2019 19:04:49.386 - Add Json firmware manifest from {indexcontroller}/firmware/manifest.vrfirmware
Tue Oct 01 2019 19:04:49.386 - Add Json firmware manifest from {indexhmd}/firmware/manifest.vrfirmware
Tue Oct 01 2019 19:04:49.387 - Add Json firmware manifest from {lighthouse}/firmware/manifest.vrfirmware
Tue Oct 01 2019 19:04:49.387 - Web language is english
Tue Oct 01 2019 19:04:49.387 - [Web] Starting web server on port localhost:8998
Tue Oct 01 2019 19:04:49.394 - New Connect message from C:\WINDOWS\SysWOW64\rundll32.exe (VRApplication_Utility) (Args: D:\games\steam\steamapps\common\MixedRealityVRDriver\bin\win32\driver_holographic.dll,_ProcessFileChangeNotification@16) 30340 
Tue Oct 01 2019 19:04:49.399 - Creating builtin app for C:\WINDOWS\SysWOW64\rundll32.exe (VRApplication_Utility)
Tue Oct 01 2019 19:04:49.399 - Setting app system.generated.rundll32.exe PID to 30340
Tue Oct 01 2019 19:04:49.399 - Enabling legacy input for system.generated.rundll32.exe
Tue Oct 01 2019 19:04:49.400 - Skipping driver load for application rundll32 (30340) because it is a utility
Tue Oct 01 2019 19:04:49.401 - Processing message VRMsg_Connect from rundll32 (30340) took 0.00664 seconds
Tue Oct 01 2019 19:04:49.983 - Closing pipe rundll32 (30340) because it was broken from the other end
Tue Oct 01 2019 19:04:49.983 - Process rundll32 (30340) disconnected (Thread(0x000001E7A799AFD0/0x000)
Tue Oct 01 2019 19:04:49.983 - Clearing application system.generated.rundll32.exe PID because 30340 has exited
Tue Oct 01 2019 19:04:50.677 - [Steam] Steam INIT.
Tue Oct 01 2019 19:04:51.987 - Shutting down server after 2.592792 seconds. Recent Disconnect: false; Waiting for connection statuses: Foreground: 0 Monitor: 0 Web: 0
Tue Oct 01 2019 19:04:51.987 - VR server shutting down
Tue Oct 01 2019 19:04:51.987 - [Web] Shutting down web server.
Tue Oct 01 2019 19:04:52.128 - Listener thread ending
Tue Oct 01 2019 19:04:52.198 - CSharedResourceNamespaceServer shutting down
Tue Oct 01 2019 19:04:52.199 - [vrserver] Graceful exit

**Comment by sergioberg** [comment]
Tue Oct 01 2019 19:04:49.394 - New Connect message from C:\WINDOWS\SysWOW64\rundll32.exe (VRApplication_Utility) (Args: D:\games\steam\steamapps\common\MixedRealityVRDriver\bin\win32\driver_holographic.dll,_ProcessFileChangeNotification@16) 30340

This seems to be related to "Windows Mixed Reality for SteamVR"
After switching to Steam beta, Steam for some reason “forgot” that it has “Windows Mixed Reality for SteamVR” installed.
I installed it again. Now Steam can not delete it giving an error.

![image](https://user-images.githubusercontent.com/12216723/65973380-a8c7e780-e484-11e9-9279-584fd9aada0f.png)

**Comment by sergioberg** [comment]
Manually removing "Windows Mixed Reality for SteamVR" helps.
If I try to install "Windows Mixed Reality for SteamVR" again, it leads to the same problems: it is impossible to launch "SteamVR" and it is not possible to remove "Windows Mixed Reality for SteamVR"
In addition to Index, I have Lenovo WMR and Vive Pro

**Comment by BPHardware** [comment]
Similar reports here: 
https://help.steampowered.com/en/ticketmaster/ticket/HT-V9KC-NQ69-JJMX (requires Ticketmaster access)

https://steamcommunity.com/app/250820/discussions/3/1626286205690317898/

https://steamcommunity.com/groups/SteamClientBeta/discussions/0/1627412171718764182/

**Comment by sergioberg** [comment]
@BPHardware @KWS-Compat 
Yes, "Windows Mixed Reality for SteamVR" triggers this issue but issue is not compleatly gone if remove WMR app. 
This is Steam beta issue, not the "Windows Mixed Reality for SteamVR". After most VR sessions after closing SteamVR  Steam is still showing that SteamVR is running with no proccess of SteamVR. 
Without "Windows Mixed Reality for SteamVR" i can at least restart Steam to fix it. But it is not solve issue compleatly.
