### ISSUE TITLE
SteamVR: VR Applications that were launched prior to launching SteamVR will fail to correctly close.

### ISSUE THREAD

**Issue by KWS-Compat** [ValveSoftware/VR-Community-Bugs#26]
**SteamVR:** If the user launches any VR Game before launching SteamVR, the program will fail to close correctly. Attempting to close the application will return to the user to SteamVR Home, but the application will still be marked as running in the SteamVR Library. Attempting to re-launch the application will result in a message informing the user the application is already running.

**Repro Steps:**
1. Ensure SteamVR is not running.
2. In the Steam Library, launch any VR application (Except for SteamVR Home)
3. Once the application has loaded, attempt to quit. Observe the application is still marked as 'running' in the Steam Library.
4. Attempt to re-launch the application. Observe the error message informing the user that the application is already running.

**Expected Results:**
Application and all associated processes close smoothly.
**Actual Result:**
Application fails to close effectively and is noted as still running.

**Config Details:**
Issue does not appear to be hardware based, as it was reproduced on all tested hardware and HMDs.

Tested CPUs:
AMD Ryzen 7 1700
Intel Core i7-8700K

Tested GPUs:
NVidia GTX 970
GeForceGTX 980

Tested HMDs:
Oculus Rift
HTC Vive
WMR

SteamVR Beta Build: 3024311
SteamVR Stable Build: 3013217

**Comment by BPHardware** [comment]
Appears to be related to Unity titles specifically - 
https://steamcommunity.com/app/358720/discussions/0/2590022385658996090/

**Comment by KWS-Compat** [comment]
> Appears to be related to Unity titles specifically -
> https://steamcommunity.com/app/358720/discussions/0/2590022385658996090/

According to the first and final posts in the linked thread, the issue is also appearing to affect Unreal Engine 4 titles. Is there additional context provided in another thread?

**Comment by BPHardware** [comment]
I misread the posts, sorry for the confusion.

**Comment by KWS-Compat** [comment]
As of SteamVR Beta version 1539100633, the behaviour of this issue has changed slightly. In previous version the compositor would crash. As of the new update the compositor no longer crashes and the user is correctly returned to the SteamVR Home, however the title continues to run and its audio can still be heard.

**Comment by JoeLudwig** [comment]
This should be fixed now, at least in Main. The fix will be in a beta update soon.

If you see something like this again, please open a new bug. It's not at all clear that the original bug from 8/14 and the regression from 10/26 are the same thing.
