### ISSUE TITLE
SteamVR: Vive Pro camera is misaligned when viewed through the Chaperone Bounds system

### ISSUE THREAD

**Issue by BPHardware** [ValveSoftware/VR-Community-Bugs#52]
Issue: The Vive Pro camera is misaligned when viewed through the Chaperone Bounds system.

Steam Client Version: 10/30/2018
SteamVR Version: 10/31/2018

VR Equipment: Vive Pro

Community Source Links: https://steamcommunity.com/app/250820/discussions/3/1728711392745074445/

Repro Steps:

1. Launch SteamVR
2. From SteamVR Home, open the Dashboard and navigate to the 'Settings' tab 
3. Select 'Camera' 
4. Ensure that the 'Use camera for Chaperone Bounds' option is enabled
5. Open the SteamVR dashboard to enable the cameras view port
6. Place the view port in front of you so it is centered with your vision
7. Hold up your other hand so that it can be viewed through the view port
8. Notice the camera is misaligned 

Expected: Camera should be aligned and centered with the users vision.

Encountered: Camera is misaligned and is skewed by about 30 degrees when viewed through the chaperone system.

Notes:

**Comment by KWS-Compat** [comment]
Issue is no longer occurring as of SteamVR Version 1.1.4

**Comment by KWS-Compat** [comment]
The issue was observed to no longer occur as it was addressed in SteamVR Beta Build 1.3.15.

**Comment by kisak-valve** [comment]
Closing per "Vive Pro: Greatly increased FOV of PIP camera view, and centered it correctly." in [SteamVR  Beta 1.3.15](https://steamcommunity.com/games/250820/announcements/detail/1806413264814962064) update and the last comment.
