### ISSUE TITLE
SteamVR: Controller Bindings tab does not function.

### ISSUE THREAD

**Issue by KWS-Compat** [ValveSoftware/VR-Community-Bugs#62]
When attempting to open the Controller tab of the Steam Overlay, the user will be presented with a black panel, and will be unable to interact with or adjust the controller bindings.

![steamvr - controller binding](https://user-images.githubusercontent.com/41118265/48713800-3be68e80-ebdf-11e8-9b27-0eddb0250d37.jpg)

Repro Steps:
1. Launch SteamVR
2. Wait for SteamVR Home to be displayed in the HMD
3. Click on the Thumbstick button on either controller to bring up Steam Overlay menu
4. Select Controller Binding tab. Observe that the feature is not functional.

Expected Result:
The Controller Binding menu is displayed and the user can modify the controller bindings.
Actual Result:
Upon clicking on the Controller Binding tab, a black window pops up and the controller binding screen does not display.

Repro Rate: 10/10

Config Details:
Tested CPU:  AMD Threadripper Ryzen 1950X, AMD Ryzen 7 1700
Tested GPU: Nvidia GTX 1080 Ti, Radeon RX 580
Tested HMD: Samsung Odysey WMR, Oculus Rift, HTC Vive

SteamVR (Beta) Build: 3315642

**Comment by kisak-valve** [comment]
Per "Fixed issue with controller binding and tracking management UIs showing up as a black screen." in the [2018-11-20](https://steamcommunity.com/games/250820/announcements/detail/3038136886322358281) SteamVR beta update (and https://github.com/ValveSoftware/openvr/issues/942#issuecomment-440365975), please retest this issue.

**Comment by KWS-Compat** [comment]
We have regressed this issue on all affected HMDs, and have confirmed that it is No Longer Occurring as of  11/20/2018. Closing the issue as Fixed.
