### ISSUE TITLE
Controller Configuration tool fails to initialize when using Russian language

### ISSUE THREAD

**Issue by BPHardware** [ValveSoftware/VR-Community-Bugs#76]
When the Steam Client (and by extension the SteamVR client) are set to use the Russian localization, the SteamVR Input configuration tool fails to initialize correctly and shows a blank black window instead.

Steps for repro: 

- Open Steam Client, go to Steam menu > Settings > Interface, and set the language to 'Russian' 
- Press 'Restart Steam' to complete the switch
- After Steam has restarted, launch SteamVR, and open the Configuration tool

Expected result - Configuration tool launches as expected
Actual result - Configuration tool window launches, however window is blank

Additional notes: Tested on a variety of languages, (including Ukrainian and other non-latin languages) however only Russian exhibited this issue. Also, an additional dashboard option for the configuration tool appears on dashboard (and is a bit larger than normal, for some reason), and it looks like other UI elements are incorrectly sized as well, however this dashboard also has the same symptoms. 

Web server log in SteamVR report shows the following line:
Wed Dec 05 2018 11:58:51.722 - Console Message: FAILED TO INITIALIZE BINDINGUI - http://localhost:8998/dashboard/controllerbindingui.ad75be5a7ad9c6c96dd6.js:5

Tested on 1.1.4, unable to revert to different build at the moment, however previously experienced the issue on 1.1.3 as well. Duplicated on both stable and Beta Steam client too.

**Comment by KWS-Compat** [comment]
We have tested this issue against mutliple configurations and HMDs, and have confirmed that it is occurring across all tested devices.

Additionally, this issue appears to be related to Issue #62, which observed similar behaviour on the English Language. 

Config Details:
Tested CPU: AMD Threadripper Ryzen 1950X, AMD Ryzen 7 1700
Tested GPU: Nvidia GTX 1080 Ti, Radeon RX 580
Tested HMD: Samsung Odysey WMR, Oculus Rift, HTC Vive

**Comment by KWS-Compat** [comment]
A master ticket has been created for this issue across all languages, ticket #84.

**Comment by KWS-Compat** [comment]
Issue was observed to no longer occur as of SteamVR Beta Build 1.3.7 for Russian language and other affected languages in ticket #84

**Comment by kisak-valve** [comment]
Closing per the last comment.
