### ISSUE TITLE
SteamVR: Launching Controller Binding menu will leave a black and non-functional menu on certain languages.

### ISSUE THREAD

**Issue by KWS-Compat** [ValveSoftware/VR-Community-Bugs#84]
When the user attempts to bind their controllers in SteamVR Controller Binding option, a black and non-functional menu will appear. This issue only occurs on the following languages:
- Russian
- Korean
- Spanish (Latin)
- Romanian

![ru steamvr - non-functional controller binding menu](https://user-images.githubusercontent.com/41118265/50016751-178c9080-ff98-11e8-8e16-d3492cea1cb3.jpg)

**Repro Steps:**
1. Launch Steam Client.
2. Launch Steam Settings.
3. Select ' Interface' tab and change the language to the affected language.
4. Restart Steam Client.
5. Launch SteamVR.
6. Open SteamVR Overlay.
7. Select Settings.
8. Select 'Controller Binding'. Observe that upon launch, a black and non-functional menu pops up.

**Repro Rate:** 10/10

**Note:**
- An additional button for Controller Binding  appears on the Dashboard, which also leaves a black and non-functional window upon launch.

**Expected Result:**
The Controller Binding menu to be functional and accessible.
**Actual Result:**
The Controller Binding menu is a black and non-functional window.

**Config Details:**
Issue occurs across all hardware and HMDs.

**SteamVR Beta Build:** 1.2.1

**Comment by kisak-valve** [comment]
Also reported at https://github.com/ValveSoftware/openvr/issues/961.

**Comment by KWS-Compat** [comment]
Issue still occurs as written as of SteamVR Beta Build: 1.2.7 and SteamVR Stable Build: 1.2.7

**Comment by KWS-Compat** [comment]
The issue is still occurring as of SteamVR Beta Build: 1.3.1. However, the additional button for Controller Binding menu is no longer on the SteamVR Overlay.

**Comment by KWS-Compat** [comment]
Issue was observed to no longer occur as of SteamVR Beta Build 1.3.7 for all affected languages.
